name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Generate README file
        run: |-
          npm start
      - name: Commit with diff
        run: |-
          git status
          git branch -a
          git add README.md
          # git diff
          # git config --global user.email "hello@girlsincode.com"
          # git config --global user.name "ReadMe Bot"
          git commit -m ":sparkles: feat(README.md): Updated README" || echo "No changes detected"
          git push